#define VERSION_MAJOR 2
#define VERSION_MINOR 99
#define VERSION_PATCH 99
#define VERSION_BUILD 99

#define FIX_VERSION_MAJOR VERSION_MAJOR
#define FIX_VERSION_MINOR VERSION_MINOR
#define FIX_VERSION_PATCH VERSION_PATCH
#define FIX_VERSION_BUILD VERSION_BUILD

#define UKEY_VERSION_MAJOR 1
#define UKEY_VERSION_MINOR 5
#define UKEY_VERSION_PATCH 0
#define UKEY_VERSION_BUILD 0

#define _STR(X) #X
#define VERSTR(X) _STR(X)

#define UKEY_VERSION         \
  VERSTR(UKEY_VERSION_MAJOR) \
  "." VERSTR(UKEY_VERSION_MINOR) "." VERSTR(UKEY_VERSION_PATCH)
